# Generated by Django 4.0.7 on 2024-01-30 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modified in')),
                ('ativo', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('cnpj', models.CharField(max_length=15, verbose_name='CNPJ Number')),
                ('road', models.CharField(max_length=255, verbose_name='Road Name')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Neighborhood Name')),
                ('house_number', models.IntegerField(verbose_name='House Number')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
            },
        ),
    ]
