# Generated by Django 4.0.7 on 2024-01-31 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prohibited',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modified in')),
                ('ativo', models.BooleanField(default=True, verbose_name='Active?')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Prohibited',
                'verbose_name_plural': 'Prohibiteds',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modified in')),
                ('ativo', models.BooleanField(default=True, verbose_name='Active?')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Prohibited',
                'verbose_name_plural': 'Prohibiteds',
                'ordering': ('date',),
            },
        ),
    ]
