# Generated by Django 4.0.7 on 2024-02-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exit',
            options={'ordering': ('date',), 'verbose_name': 'Exit', 'verbose_name_plural': 'Exits'},
        ),
    ]
