# Generated by Django 4.0.7 on 2024-01-30 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modified in')),
                ('ativo', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(upload_to='media')),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Average Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
