# Generated by Django 4.0.7 on 2024-01-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Url Image'),
        ),
    ]
